[build]
  command = "npm run build"
  publish = "out"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
package = "netlify-plugin-image-optim"

[[plugins]]
package = "netlify-plugin-cache-nextjs"

[[plugins]]
package = 'netlify-plugin-contextual-env'
  [plugins.inputs]
  mode = 'prefix'